version: "3"
services:
  app:
    build: ./app
    ports:
      - "3000:80"
    networks:
      - services
    volumes:
      - './app/config:/etc/nginx/conf.d'
  auth-service:
    build: ./auth-service
    networks:
      - services
    volumes:
      - ./auth-service:/src
  course-service:
    build: ./course-service
    networks:
      - services
    volumes:
      - ./course-service:/src
  review-service:
    build: ./review-service
    networks:
      - services
    volumes:
      - ./review-service:/src
  user-service:
    build: ./user-service
    networks:
      - services
    volumes:
      - ./user-service:/src
networks:
  services: