version: "3"
services:
  app:
    build: ./app
    ports:
      - "3000:80"
    networks:
      - services
    volumes:
      - './app/config:/etc/nginx/conf.d'
  service:
    build: ./service
    networks:
      - services
    volumes:
      - ./service:/src
networks:
  services: